/**
 * BRISTI 50-product catalog source of truth.
 *
 * Extracted verbatim from BRISTI_50_Product_Catalog(1).xlsx. Every field is
 * treated exactly as provided — names, descriptions, prices, category names,
 * SEO fields and option values are NOT rewritten, shortened or corrected.
 *
 * `optionsText` uses the spreadsheet's notation:
 *   "Color: Black, White | Size: S, M, L, XL"
 * meaning Color=[Black, White] and Size=[S, M, L, XL].
 */
export interface CatalogProduct {
  n: number;
  sku: string;
  name: string;
  shortDescription: string;
  description: string;
  price: number;
  compareAtPrice: number;
  costPrice: number;
  category: string;
  seoTitle: string;
  seoDescription: string;
  seoKeywords: string;
  optionsText: string;
}

export const CATALOG: CatalogProduct[] = [
  {
    n: 1,
    sku: "BT-OT-001",
    name: "Noir Essential Oversized Tee",
    shortDescription: "Relaxed-fit premium oversized T-shirt with a clean monochrome aesthetic.",
    description: "A heavyweight-inspired everyday tee designed with dropped shoulders, a relaxed silhouette and minimal branding. Made for elevated casual styling and effortless layering.",
    price: 1499,
    compareAtPrice: 1999,
    costPrice: 620,
    category: "Oversized T-Shirts",
    seoTitle: "BRISTI Noir Essential Oversized Tee | Premium Men's Oversized T-Shirt",
    seoDescription: "Shop the BRISTI Noir Essential Oversized Tee, a premium relaxed-fit men's oversized T-shirt designed for modern everyday luxury.",
    seoKeywords: "BRISTI oversized t-shirt, premium men's t-shirt, black oversized tee, luxury streetwear, men's fashion India",
    optionsText: "Color: Black, White, Charcoal | Size: S, M, L, XL",
  },
  {
    n: 2,
    sku: "BT-OT-002",
    name: "Ivory Cloud Oversized Tee",
    shortDescription: "Soft ivory oversized tee with a clean, premium silhouette.",
    description: "An understated ivory T-shirt with dropped shoulders and a generous relaxed fit. Designed to pair effortlessly with tailored trousers, cargos and denim.",
    price: 1599,
    compareAtPrice: 2099,
    costPrice: 660,
    category: "Oversized T-Shirts",
    seoTitle: "BRISTI Ivory Cloud Oversized Tee | Premium Men's T-Shirt",
    seoDescription: "Discover the BRISTI Ivory Cloud Oversized Tee, a refined oversized men's T-shirt for minimalist premium wardrobes.",
    seoKeywords: "ivory oversized t-shirt, premium men's clothing, luxury t-shirt India, minimalist menswear, BRISTI",
    optionsText: "Color: Ivory, Sand | Size: S, M, L, XL",
  },
  {
    n: 3,
    sku: "BT-OT-003",
    name: "Graphite Signature Tee",
    shortDescription: "A dark graphite oversized tee built for understated everyday style.",
    description: "Cut in a contemporary relaxed silhouette, the Graphite Signature Tee brings depth to casual wardrobes with a clean finish and subtle BRISTI identity.",
    price: 1699,
    compareAtPrice: 2199,
    costPrice: 700,
    category: "Oversized T-Shirts",
    seoTitle: "BRISTI Graphite Signature Tee | Luxury Oversized Men's T-Shirt",
    seoDescription: "Explore the BRISTI Graphite Signature Tee, a premium graphite oversized T-shirt with a contemporary relaxed silhouette.",
    seoKeywords: "graphite oversized t-shirt, luxury men's tee, premium menswear, dark oversized t-shirt, BRISTI India",
    optionsText: "Color: Graphite, Black | Size: S, M, L, XL",
  },
  {
    n: 4,
    sku: "BT-OT-004",
    name: "Stone Relaxed Tee",
    shortDescription: "Neutral stone oversized T-shirt with an effortless luxury feel.",
    description: "A versatile stone-toned oversized tee designed around clean lines and relaxed proportions. Ideal for monochrome outfits and everyday premium dressing.",
    price: 1549,
    compareAtPrice: 1999,
    costPrice: 640,
    category: "Oversized T-Shirts",
    seoTitle: "BRISTI Stone Relaxed Tee | Premium Oversized Menswear",
    seoDescription: "Meet the BRISTI Stone Relaxed Tee, a neutral premium oversized men's T-shirt designed for effortless modern styling.",
    seoKeywords: "stone oversized t-shirt, neutral men's fashion, premium relaxed tee, luxury casualwear, BRISTI",
    optionsText: "Color: Stone, Beige | Size: S, M, L, XL",
  },
  {
    n: 5,
    sku: "BT-OT-005",
    name: "Midnight Frame Tee",
    shortDescription: "Deep black oversized tee with a structured contemporary profile.",
    description: "The Midnight Frame Tee combines a relaxed oversized fit with a sharper visual profile, making it an easy foundation for elevated streetwear and evening casual looks.",
    price: 1699,
    compareAtPrice: 2299,
    costPrice: 710,
    category: "Oversized T-Shirts",
    seoTitle: "BRISTI Midnight Frame Tee | Premium Black Oversized T-Shirt",
    seoDescription: "Buy the BRISTI Midnight Frame Tee, a premium black oversized men's T-shirt made for elevated contemporary style.",
    seoKeywords: "black oversized t-shirt, premium black tee, luxury streetwear India, men's oversized clothing, BRISTI",
    optionsText: "Color: Black, Washed Black | Size: S, M, L, XL",
  },
  {
    n: 6,
    sku: "BT-OT-006",
    name: "Sage Form Oversized Tee",
    shortDescription: "Muted sage oversized tee with a refined contemporary character.",
    description: "A soft muted-green statement piece designed with relaxed proportions and a clean finish. A modern essential for neutral and earthy wardrobes.",
    price: 1649,
    compareAtPrice: 2149,
    costPrice: 680,
    category: "Oversized T-Shirts",
    seoTitle: "BRISTI Sage Form Oversized Tee | Premium Men's Fashion",
    seoDescription: "Discover the BRISTI Sage Form Oversized Tee, a refined muted-sage oversized T-shirt for modern men's wardrobes.",
    seoKeywords: "sage oversized t-shirt, premium men's fashion, green oversized tee, contemporary menswear, BRISTI",
    optionsText: "Color: Sage, Olive | Size: S, M, L, XL",
  },
  {
    n: 7,
    sku: "BT-JT-001",
    name: "Tokyo Pleat Trouser",
    shortDescription: "Relaxed Japanese-inspired trouser with architectural pleats.",
    description: "A contemporary trouser built around clean pleats, a comfortable straight-to-relaxed profile and a refined drape. Designed for modern tailoring with an effortless attitude.",
    price: 2499,
    compareAtPrice: 3299,
    costPrice: 1080,
    category: "Japanese Trouser",
    seoTitle: "BRISTI Tokyo Pleat Trouser | Japanese Inspired Men's Trousers",
    seoDescription: "Shop the BRISTI Tokyo Pleat Trouser, a premium Japanese-inspired men's trouser with architectural pleats and relaxed tailoring.",
    seoKeywords: "Japanese trousers men, pleated trousers, premium men's trousers, relaxed tailoring, BRISTI",
    optionsText: "Color: Black, Charcoal | Waist: 30, 32, 34, 36",
  },
  {
    n: 8,
    sku: "BT-JT-002",
    name: "Kyoto Tailored Trouser",
    shortDescription: "Refined wide-leg trouser inspired by modern Japanese tailoring.",
    description: "Designed with a fluid silhouette and precise detailing, the Kyoto Tailored Trouser balances structure with comfort for elevated day-to-evening dressing.",
    price: 2699,
    compareAtPrice: 3499,
    costPrice: 1160,
    category: "Japanese Trouser",
    seoTitle: "BRISTI Kyoto Tailored Trouser | Premium Japanese Style",
    seoDescription: "Discover BRISTI Kyoto Tailored Trouser, a refined wide-leg men's trouser inspired by modern Japanese tailoring.",
    seoKeywords: "Japanese style trousers, wide leg trousers men, luxury menswear, tailored trousers India, BRISTI",
    optionsText: "Color: Black, Beige | Waist: 30, 32, 34, 36",
  },
  {
    n: 9,
    sku: "BT-JT-003",
    name: "Zen Wide Trouser",
    shortDescription: "Minimal wide-leg trouser created for clean contemporary silhouettes.",
    description: "The Zen Wide Trouser delivers a relaxed leg line and minimalist profile, pairing naturally with oversized tees, shirts and structured outerwear.",
    price: 2399,
    compareAtPrice: 3199,
    costPrice: 1020,
    category: "Japanese Trouser",
    seoTitle: "BRISTI Zen Wide Trouser | Minimal Premium Men's Trousers",
    seoDescription: "Elevate your wardrobe with the BRISTI Zen Wide Trouser, a minimalist wide-leg men's trouser for contemporary styling.",
    seoKeywords: "wide leg men's trousers, Japanese trousers India, minimalist menswear, premium trousers, BRISTI",
    optionsText: "Color: Black, Stone | Waist: 30, 32, 34, 36",
  },
  {
    n: 10,
    sku: "BT-JT-004",
    name: "Sora Utility Trouser",
    shortDescription: "Relaxed Japanese-inspired trouser combining utility details with refined tailoring.",
    description: "Sora brings practical detailing into a premium silhouette, featuring a relaxed profile and clean construction designed for versatile city dressing.",
    price: 2599,
    compareAtPrice: 3399,
    costPrice: 1110,
    category: "Japanese Trouser",
    seoTitle: "BRISTI Sora Utility Trouser | Premium Japanese Men's Wear",
    seoDescription: "Shop BRISTI Sora Utility Trouser, a relaxed Japanese-inspired men's trouser combining utility details and modern tailoring.",
    seoKeywords: "utility trousers men, Japanese trousers, premium cargo-inspired trousers, modern menswear, BRISTI",
    optionsText: "Color: Charcoal, Olive | Waist: 30, 32, 34, 36",
  },
  {
    n: 11,
    sku: "BT-JT-005",
    name: "Kuro Tapered Trouser",
    shortDescription: "Modern black tapered trouser with a Japanese-inspired clean profile.",
    description: "A sharp yet relaxed trouser featuring a tapered leg, considered proportions and a versatile black finish for premium everyday dressing.",
    price: 2499,
    compareAtPrice: 3299,
    costPrice: 1070,
    category: "Japanese Trouser",
    seoTitle: "BRISTI Kuro Tapered Trouser | Premium Black Men's Trousers",
    seoDescription: "Discover BRISTI Kuro Tapered Trouser, a premium black men's trouser with a modern Japanese-inspired tapered silhouette.",
    seoKeywords: "black tapered trousers men, Japanese menswear, premium black trousers, luxury clothing India, BRISTI",
    optionsText: "Color: Black | Waist: 30, 32, 34, 36",
  },
  {
    n: 12,
    sku: "BT-JT-006",
    name: "Mori Pleated Trouser",
    shortDescription: "Earth-toned pleated trouser with a relaxed premium fit.",
    description: "Mori blends a warm earthy palette with structured pleats and a comfortable relaxed silhouette, creating an elevated alternative to everyday trousers.",
    price: 2549,
    compareAtPrice: 3349,
    costPrice: 1090,
    category: "Japanese Trouser",
    seoTitle: "BRISTI Mori Pleated Trouser | Premium Relaxed Men's Trousers",
    seoDescription: "Explore the BRISTI Mori Pleated Trouser, a premium earth-toned men's trouser with relaxed Japanese-inspired proportions.",
    seoKeywords: "brown pleated trousers, Japanese style menswear, premium trousers, relaxed fit men, BRISTI",
    optionsText: "Color: Brown, Taupe | Waist: 30, 32, 34, 36",
  },
  {
    n: 13,
    sku: "BT-GP-001",
    name: "Regal Gurkha Pant",
    shortDescription: "Structured Gurkha pant with a distinctive double-waist fastening.",
    description: "A modern interpretation of the classic Gurkha silhouette, designed with a strong waistband, pleated front and relaxed leg for confident contemporary dressing.",
    price: 2299,
    compareAtPrice: 2999,
    costPrice: 980,
    category: "Gurkha Pant",
    seoTitle: "BRISTI Regal Gurkha Pant | Premium Men's Gurkha Trousers",
    seoDescription: "Shop the BRISTI Regal Gurkha Pant, a premium men's trouser with a distinctive Gurkha waistband and modern relaxed fit.",
    seoKeywords: "Gurkha pants men, premium Gurkha trousers, men's tailored pants, luxury menswear India, BRISTI",
    optionsText: "Color: Black, Navy | Waist: 30, 32, 34, 36",
  },
  {
    n: 14,
    sku: "BT-GP-002",
    name: "Navy Heritage Gurkha",
    shortDescription: "Classic navy Gurkha pant reimagined for modern wardrobes.",
    description: "A deep navy Gurkha trouser with heritage-inspired construction and contemporary proportions, designed to transition from smart casual to occasion dressing.",
    price: 2399,
    compareAtPrice: 3099,
    costPrice: 1020,
    category: "Gurkha Pant",
    seoTitle: "BRISTI Navy Heritage Gurkha Pant | Premium Men's Trousers",
    seoDescription: "Discover the BRISTI Navy Heritage Gurkha Pant, a premium navy trouser blending classic Gurkha heritage with modern tailoring.",
    seoKeywords: "navy Gurkha pants, premium navy trousers men, Gurkha trousers India, modern menswear, BRISTI",
    optionsText: "Color: Navy | Waist: 30, 32, 34, 36",
  },
  {
    n: 15,
    sku: "BT-GP-003",
    name: "Black Command Gurkha",
    shortDescription: "Bold black Gurkha pant with a clean military-inspired silhouette.",
    description: "Designed for a strong presence, Black Command combines a structured waistband, pleats and a relaxed straight leg in a versatile black finish.",
    price: 2399,
    compareAtPrice: 3099,
    costPrice: 1010,
    category: "Gurkha Pant",
    seoTitle: "BRISTI Black Command Gurkha Pant | Luxury Men's Gurkha Trousers",
    seoDescription: "Buy BRISTI Black Command Gurkha Pant, a premium black men's trouser inspired by classic military tailoring.",
    seoKeywords: "black Gurkha pants, military inspired trousers, premium men's black trousers, luxury menswear, BRISTI",
    optionsText: "Color: Black | Waist: 30, 32, 34, 36",
  },
  {
    n: 16,
    sku: "BT-GP-004",
    name: "Olive Officer Gurkha",
    shortDescription: "Earthy olive Gurkha pant combining heritage styling with modern comfort.",
    description: "An olive-toned statement trouser with a distinctive waist treatment and relaxed silhouette, designed for contemporary utility-luxury looks.",
    price: 2349,
    compareAtPrice: 3049,
    costPrice: 990,
    category: "Gurkha Pant",
    seoTitle: "BRISTI Olive Officer Gurkha Pant | Premium Men's Fashion",
    seoDescription: "Explore BRISTI Olive Officer Gurkha Pant, a premium olive men's trouser with heritage-inspired Gurkha detailing.",
    seoKeywords: "olive Gurkha trousers, utility menswear, premium olive pants, Gurkha style India, BRISTI",
    optionsText: "Color: Olive | Waist: 30, 32, 34, 36",
  },
  {
    n: 17,
    sku: "BT-GP-005",
    name: "Sand Commander Pant",
    shortDescription: "Warm sand Gurkha pant with an elevated relaxed silhouette.",
    description: "A versatile neutral trouser featuring a structured Gurkha waistband and clean pleated front, designed for effortless premium summer styling.",
    price: 2299,
    compareAtPrice: 2999,
    costPrice: 970,
    category: "Gurkha Pant",
    seoTitle: "BRISTI Sand Commander Gurkha Pant | Premium Men's Trousers",
    seoDescription: "Shop BRISTI Sand Commander Gurkha Pant, a premium sand-coloured trouser designed for refined modern menswear.",
    seoKeywords: "sand Gurkha pants, beige men's trousers, premium neutral menswear, Gurkha trousers, BRISTI",
    optionsText: "Color: Sand, Beige | Waist: 30, 32, 34, 36",
  },
  {
    n: 18,
    sku: "BT-GP-006",
    name: "Monarch Gurkha Pant",
    shortDescription: "Refined charcoal Gurkha trouser with a strong tailored character.",
    description: "Monarch combines a sophisticated charcoal tone with a distinctive Gurkha closure and structured pleats for a polished contemporary silhouette.",
    price: 2449,
    compareAtPrice: 3199,
    costPrice: 1030,
    category: "Gurkha Pant",
    seoTitle: "BRISTI Monarch Gurkha Pant | Premium Charcoal Men's Trousers",
    seoDescription: "Discover the BRISTI Monarch Gurkha Pant, a premium charcoal trouser with refined Gurkha tailoring and modern proportions.",
    seoKeywords: "charcoal Gurkha pants, premium tailored trousers men, luxury Gurkha trousers, BRISTI menswear",
    optionsText: "Color: Charcoal | Waist: 30, 32, 34, 36",
  },
  {
    n: 19,
    sku: "BT-SH-001",
    name: "Noir Utility Shacket",
    shortDescription: "Structured black shacket designed as a versatile premium layer.",
    description: "A refined overshirt-jacket hybrid with a clean front, practical pockets and a structured silhouette. Built for layering across seasons.",
    price: 2799,
    compareAtPrice: 3699,
    costPrice: 1250,
    category: "Shackets",
    seoTitle: "BRISTI Noir Utility Shacket | Premium Black Men's Shacket",
    seoDescription: "Shop the BRISTI Noir Utility Shacket, a premium black men's shacket designed for versatile contemporary layering.",
    seoKeywords: "black shacket men, premium shacket India, men's utility jacket, luxury layering, BRISTI",
    optionsText: "Color: Black | Size: S, M, L, XL",
  },
  {
    n: 20,
    sku: "BT-SH-002",
    name: "Cocoa Frame Shacket",
    shortDescription: "Rich brown shacket with a refined structured silhouette.",
    description: "The Cocoa Frame Shacket brings warmth and depth to transitional wardrobes with its sophisticated brown tone, clean construction and versatile layering profile.",
    price: 2899,
    compareAtPrice: 3799,
    costPrice: 1290,
    category: "Shackets",
    seoTitle: "BRISTI Cocoa Frame Shacket | Premium Brown Men's Shacket",
    seoDescription: "Discover the BRISTI Cocoa Frame Shacket, a premium brown men's layering piece with a refined contemporary silhouette.",
    seoKeywords: "brown shacket men, premium brown jacket, men's overshirt jacket, luxury menswear, BRISTI",
    optionsText: "Color: Brown, Chocolate | Size: S, M, L, XL",
  },
  {
    n: 21,
    sku: "BT-SH-003",
    name: "Slate Overshirt Shacket",
    shortDescription: "Slate-grey shacket combining overshirt ease with jacket structure.",
    description: "Designed for effortless layering, this slate shacket balances relaxed comfort with a polished shape and understated detailing.",
    price: 2749,
    compareAtPrice: 3599,
    costPrice: 1220,
    category: "Shackets",
    seoTitle: "BRISTI Slate Overshirt Shacket | Premium Men's Layer",
    seoDescription: "Elevate everyday outfits with the BRISTI Slate Overshirt Shacket, a premium grey men's layering essential.",
    seoKeywords: "grey shacket men, slate overshirt, premium men's layer, luxury casualwear, BRISTI",
    optionsText: "Color: Slate, Charcoal | Size: S, M, L, XL",
  },
  {
    n: 22,
    sku: "BT-SH-004",
    name: "Olive Field Shacket",
    shortDescription: "Muted olive shacket inspired by modern utility dressing.",
    description: "A premium utility-inspired layer with a versatile olive finish, practical pocket detailing and a relaxed contemporary fit.",
    price: 2849,
    compareAtPrice: 3749,
    costPrice: 1260,
    category: "Shackets",
    seoTitle: "BRISTI Olive Field Shacket | Premium Men's Utility Layer",
    seoDescription: "Shop the BRISTI Olive Field Shacket, a premium olive men's shacket built for contemporary utility-inspired style.",
    seoKeywords: "olive shacket, utility jacket men, premium layering India, men's field jacket, BRISTI",
    optionsText: "Color: Olive | Size: S, M, L, XL",
  },
  {
    n: 23,
    sku: "BT-SH-005",
    name: "Stone Atelier Shacket",
    shortDescription: "Light stone shacket with a clean luxury-inspired profile.",
    description: "A sophisticated neutral layer designed to work across tonal outfits. Its relaxed structure makes it ideal for effortless premium styling.",
    price: 2799,
    compareAtPrice: 3699,
    costPrice: 1240,
    category: "Shackets",
    seoTitle: "BRISTI Stone Atelier Shacket | Luxury Men's Overshirt",
    seoDescription: "Discover the BRISTI Stone Atelier Shacket, a premium stone overshirt-jacket hybrid for refined modern wardrobes.",
    seoKeywords: "stone shacket men, luxury overshirt, premium neutral jacket, modern menswear, BRISTI",
    optionsText: "Color: Stone, Beige | Size: S, M, L, XL",
  },
  {
    n: 24,
    sku: "BT-SH-006",
    name: "Midnight Layer Shacket",
    shortDescription: "Deep midnight shacket designed for sleek evening layering.",
    description: "A dark premium layer with a clean silhouette and understated detailing, designed to move seamlessly between casual and elevated looks.",
    price: 2999,
    compareAtPrice: 3899,
    costPrice: 1340,
    category: "Shackets",
    seoTitle: "BRISTI Midnight Layer Shacket | Premium Black Men's Outerwear",
    seoDescription: "Explore the BRISTI Midnight Layer Shacket, a premium dark men's outer layer designed for sophisticated styling.",
    seoKeywords: "midnight shacket, black men's outerwear, premium layer, luxury men's jacket, BRISTI",
    optionsText: "Color: Midnight, Black | Size: S, M, L, XL",
  },
  {
    n: 25,
    sku: "BT-PS-001",
    name: "Monochrome Oxford Shirt",
    shortDescription: "Premium clean-cut shirt with a timeless contemporary profile.",
    description: "A versatile wardrobe essential designed with a polished collar, refined proportions and a clean monochrome aesthetic for elevated everyday dressing.",
    price: 1999,
    compareAtPrice: 2599,
    costPrice: 820,
    category: "Premium Shirts",
    seoTitle: "BRISTI Monochrome Oxford Shirt | Premium Men's Shirt",
    seoDescription: "Shop the BRISTI Monochrome Oxford Shirt, a premium men's shirt designed for timeless contemporary dressing.",
    seoKeywords: "premium Oxford shirt men, luxury men's shirts, monochrome shirt, formal casual menswear, BRISTI",
    optionsText: "Color: White, Black | Size: S, M, L, XL",
  },
  {
    n: 26,
    sku: "BT-PS-002",
    name: "Midnight Satin Shirt",
    shortDescription: "Refined dark shirt with a subtle fluid finish for evening dressing.",
    description: "The Midnight Satin Shirt is designed for sophisticated evenings, featuring a smooth visual finish and relaxed premium silhouette.",
    price: 2199,
    compareAtPrice: 2899,
    costPrice: 900,
    category: "Premium Shirts",
    seoTitle: "BRISTI Midnight Satin Shirt | Luxury Men's Evening Shirt",
    seoDescription: "Discover the BRISTI Midnight Satin Shirt, a premium dark men's shirt designed for refined evening style.",
    seoKeywords: "black satin shirt men, luxury evening shirt, premium men's fashion, party wear men, BRISTI",
    optionsText: "Color: Black, Midnight | Size: S, M, L, XL",
  },
  {
    n: 27,
    sku: "BT-PS-003",
    name: "Ivory Resort Shirt",
    shortDescription: "Relaxed ivory shirt designed for effortless premium resort styling.",
    description: "A clean, relaxed shirt with a sophisticated ivory palette, designed to pair with tailored trousers and premium casual separates.",
    price: 1999,
    compareAtPrice: 2599,
    costPrice: 810,
    category: "Premium Shirts",
    seoTitle: "BRISTI Ivory Resort Shirt | Premium Relaxed Men's Shirt",
    seoDescription: "Elevate your wardrobe with the BRISTI Ivory Resort Shirt, a premium relaxed men's shirt for refined casual dressing.",
    seoKeywords: "ivory shirt men, resort shirt, premium casual shirt, luxury menswear India, BRISTI",
    optionsText: "Color: Ivory, Cream | Size: S, M, L, XL",
  },
  {
    n: 28,
    sku: "BT-PS-004",
    name: "Graphite Tailored Shirt",
    shortDescription: "Modern graphite shirt with a sharp yet comfortable silhouette.",
    description: "A sophisticated dark shirt built for versatility, combining a structured appearance with an easy modern fit.",
    price: 2049,
    compareAtPrice: 2699,
    costPrice: 840,
    category: "Premium Shirts",
    seoTitle: "BRISTI Graphite Tailored Shirt | Premium Men's Fashion",
    seoDescription: "Shop the BRISTI Graphite Tailored Shirt, a premium men's shirt with a modern tailored profile.",
    seoKeywords: "graphite shirt men, premium tailored shirt, luxury men's wear, dark shirt, BRISTI",
    optionsText: "Color: Graphite, Charcoal | Size: S, M, L, XL",
  },
  {
    n: 29,
    sku: "BT-PS-005",
    name: "Sage Linen-Style Shirt",
    shortDescription: "Muted sage shirt created for breathable-looking, relaxed luxury styling.",
    description: "A calm earthy tone and relaxed profile make this shirt an easy choice for elevated daytime looks and warm-weather wardrobes.",
    price: 2099,
    compareAtPrice: 2699,
    costPrice: 850,
    category: "Premium Shirts",
    seoTitle: "BRISTI Sage Linen-Style Shirt | Premium Men's Summer Shirt",
    seoDescription: "Discover the BRISTI Sage Linen-Style Shirt, a premium men's shirt in a refined muted sage tone.",
    seoKeywords: "sage shirt men, premium summer shirt, green men's shirt, relaxed luxury fashion, BRISTI",
    optionsText: "Color: Sage, Olive | Size: S, M, L, XL",
  },
  {
    n: 30,
    sku: "BT-PS-006",
    name: "Espresso Cuban Shirt",
    shortDescription: "Statement espresso shirt with a relaxed open-collar character.",
    description: "A modern Cuban-inspired shirt designed around an easy silhouette and deep espresso colour for sophisticated casual occasions.",
    price: 2149,
    compareAtPrice: 2799,
    costPrice: 870,
    category: "Premium Shirts",
    seoTitle: "BRISTI Espresso Cuban Shirt | Premium Men's Resort Wear",
    seoDescription: "Explore the BRISTI Espresso Cuban Shirt, a premium relaxed men's shirt with an open-collar inspired silhouette.",
    seoKeywords: "Cuban collar shirt men, espresso shirt, premium resort wear, luxury casual shirt, BRISTI",
    optionsText: "Color: Espresso, Brown | Size: S, M, L, XL",
  },
  {
    n: 31,
    sku: "BT-LH-001",
    name: "Noir Signature Hoodie",
    shortDescription: "Premium black hoodie with a clean understated BRISTI aesthetic.",
    description: "Designed for elevated casualwear, the Noir Signature Hoodie combines a relaxed fit with a minimal visual identity and versatile black finish.",
    price: 2299,
    compareAtPrice: 2999,
    costPrice: 950,
    category: "Luxury Hoodies",
    seoTitle: "BRISTI Noir Signature Hoodie | Premium Black Men's Hoodie",
    seoDescription: "Shop the BRISTI Noir Signature Hoodie, a premium black men's hoodie designed for elevated everyday comfort.",
    seoKeywords: "premium black hoodie, luxury men's hoodie, minimalist hoodie, BRISTI streetwear, men's fashion India",
    optionsText: "Color: Black | Size: S, M, L, XL",
  },
  {
    n: 32,
    sku: "BT-LH-002",
    name: "Stone Luxe Hoodie",
    shortDescription: "Neutral stone hoodie designed for quiet-luxury inspired casualwear.",
    description: "A refined everyday hoodie in a versatile stone tone, designed to layer effortlessly with premium trousers, cargos and jackets.",
    price: 2399,
    compareAtPrice: 3099,
    costPrice: 990,
    category: "Luxury Hoodies",
    seoTitle: "BRISTI Stone Luxe Hoodie | Premium Men's Luxury Hoodie",
    seoDescription: "Discover the BRISTI Stone Luxe Hoodie, a premium stone men's hoodie inspired by understated luxury.",
    seoKeywords: "stone hoodie men, quiet luxury hoodie, premium casualwear, luxury menswear, BRISTI",
    optionsText: "Color: Stone, Beige | Size: S, M, L, XL",
  },
  {
    n: 33,
    sku: "BT-LH-003",
    name: "Midnight Core Hoodie",
    shortDescription: "Deep midnight hoodie with a structured contemporary fit.",
    description: "Built as a versatile wardrobe core, this dark hoodie offers a clean silhouette suitable for travel, weekends and layered city looks.",
    price: 2349,
    compareAtPrice: 3049,
    costPrice: 970,
    category: "Luxury Hoodies",
    seoTitle: "BRISTI Midnight Core Hoodie | Premium Men's Streetwear",
    seoDescription: "Shop the BRISTI Midnight Core Hoodie, a premium dark men's hoodie for modern city styling.",
    seoKeywords: "midnight hoodie men, premium streetwear, luxury hoodie India, dark hoodie, BRISTI",
    optionsText: "Color: Midnight, Black | Size: S, M, L, XL",
  },
  {
    n: 34,
    sku: "BT-LH-004",
    name: "Moss Essential Hoodie",
    shortDescription: "Muted moss hoodie adding an earthy tone to elevated casual wardrobes.",
    description: "A contemporary hoodie with a relaxed silhouette and sophisticated moss palette, designed for tonal and layered outfits.",
    price: 2399,
    compareAtPrice: 3099,
    costPrice: 980,
    category: "Luxury Hoodies",
    seoTitle: "BRISTI Moss Essential Hoodie | Premium Men's Hoodie",
    seoDescription: "Elevate everyday style with the BRISTI Moss Essential Hoodie, a premium moss-green men's hoodie.",
    seoKeywords: "moss hoodie men, green premium hoodie, luxury casualwear, modern men's fashion, BRISTI",
    optionsText: "Color: Moss, Olive | Size: S, M, L, XL",
  },
  {
    n: 35,
    sku: "BT-LH-005",
    name: "Cocoa Club Hoodie",
    shortDescription: "Rich cocoa hoodie with a sophisticated tonal aesthetic.",
    description: "The Cocoa Club Hoodie introduces warmth and depth to premium casual wardrobes with a relaxed fit and rich brown colour.",
    price: 2449,
    compareAtPrice: 3199,
    costPrice: 1000,
    category: "Luxury Hoodies",
    seoTitle: "BRISTI Cocoa Club Hoodie | Premium Brown Men's Hoodie",
    seoDescription: "Discover the BRISTI Cocoa Club Hoodie, a premium brown hoodie for refined contemporary men's style.",
    seoKeywords: "brown hoodie men, premium cocoa hoodie, luxury streetwear, men's fashion India, BRISTI",
    optionsText: "Color: Cocoa, Brown | Size: S, M, L, XL",
  },
  {
    n: 36,
    sku: "BT-LH-006",
    name: "Cloud Grey Hoodie",
    shortDescription: "Soft grey hoodie designed as an elevated everyday essential.",
    description: "A versatile grey layer with a clean silhouette, created for effortless styling across neutral and monochrome wardrobes.",
    price: 2299,
    compareAtPrice: 2999,
    costPrice: 940,
    category: "Luxury Hoodies",
    seoTitle: "BRISTI Cloud Grey Hoodie | Premium Grey Men's Hoodie",
    seoDescription: "Shop the BRISTI Cloud Grey Hoodie, a premium grey men's hoodie for minimalist everyday dressing.",
    seoKeywords: "grey hoodie men, premium hoodie, minimalist menswear, luxury casual hoodie, BRISTI",
    optionsText: "Color: Grey, Ash | Size: S, M, L, XL",
  },
  {
    n: 37,
    sku: "BT-CP-001",
    name: "Urban Black Cargo",
    shortDescription: "Premium black cargo pant with a clean contemporary utility profile.",
    description: "A modern cargo built with practical pocket detailing and a refined silhouette that balances utility with elevated streetwear aesthetics.",
    price: 2199,
    compareAtPrice: 2899,
    costPrice: 920,
    category: "Cargo Pants",
    seoTitle: "BRISTI Urban Black Cargo Pants | Premium Men's Cargo Trousers",
    seoDescription: "Shop BRISTI Urban Black Cargo Pants, premium men's cargos combining clean utility details with contemporary style.",
    seoKeywords: "black cargo pants men, premium cargos, luxury streetwear India, utility trousers, BRISTI",
    optionsText: "Color: Black | Waist: 30, 32, 34, 36",
  },
  {
    n: 38,
    sku: "BT-CP-002",
    name: "Olive Terrain Cargo",
    shortDescription: "Olive cargo pants inspired by modern utility dressing.",
    description: "A versatile olive cargo featuring functional pockets, relaxed proportions and a refined finish for everyday city wear.",
    price: 2249,
    compareAtPrice: 2949,
    costPrice: 940,
    category: "Cargo Pants",
    seoTitle: "BRISTI Olive Terrain Cargo Pants | Premium Utility Menswear",
    seoDescription: "Discover the BRISTI Olive Terrain Cargo Pants, premium men's cargos designed for modern utility-inspired styling.",
    seoKeywords: "olive cargo pants men, utility trousers, premium cargo India, men's streetwear, BRISTI",
    optionsText: "Color: Olive | Waist: 30, 32, 34, 36",
  },
  {
    n: 39,
    sku: "BT-CP-003",
    name: "Stone Utility Cargo",
    shortDescription: "Neutral stone cargo designed for elevated everyday styling.",
    description: "A clean neutral cargo that pairs utility-inspired pocketing with a refined relaxed fit for premium casual wardrobes.",
    price: 2199,
    compareAtPrice: 2899,
    costPrice: 910,
    category: "Cargo Pants",
    seoTitle: "BRISTI Stone Utility Cargo | Premium Neutral Men's Trousers",
    seoDescription: "Shop the BRISTI Stone Utility Cargo, a premium stone men's cargo pant for contemporary casual styling.",
    seoKeywords: "stone cargo pants, neutral men's trousers, premium cargo, modern menswear, BRISTI",
    optionsText: "Color: Stone, Beige | Waist: 30, 32, 34, 36",
  },
  {
    n: 40,
    sku: "BT-CP-004",
    name: "Graphite Tactical Cargo",
    shortDescription: "Dark graphite cargo with a sleek utility-inspired silhouette.",
    description: "Designed for urban dressing, this cargo combines a dark graphite tone with structured pocket detailing and a contemporary relaxed fit.",
    price: 2299,
    compareAtPrice: 2999,
    costPrice: 950,
    category: "Cargo Pants",
    seoTitle: "BRISTI Graphite Tactical Cargo | Premium Men's Cargo Pants",
    seoDescription: "Explore BRISTI Graphite Tactical Cargo, premium dark men's cargo pants with a modern utility silhouette.",
    seoKeywords: "graphite cargo pants, tactical cargo men, premium utility wear, luxury streetwear, BRISTI",
    optionsText: "Color: Graphite, Black | Waist: 30, 32, 34, 36",
  },
  {
    n: 41,
    sku: "BT-CP-005",
    name: "Sand Explorer Cargo",
    shortDescription: "Warm sand cargo pant with a relaxed premium fit.",
    description: "A neutral utility essential designed to bring a lighter tonal option to contemporary men's wardrobes.",
    price: 2249,
    compareAtPrice: 2949,
    costPrice: 930,
    category: "Cargo Pants",
    seoTitle: "BRISTI Sand Explorer Cargo | Premium Men's Utility Pants",
    seoDescription: "Discover the BRISTI Sand Explorer Cargo, a premium sand cargo pant for modern utility-inspired menswear.",
    seoKeywords: "sand cargo pants men, beige cargo trousers, premium utility pants, men's fashion India, BRISTI",
    optionsText: "Color: Sand, Beige | Waist: 30, 32, 34, 36",
  },
  {
    n: 42,
    sku: "BT-CP-006",
    name: "Midnight Flex Cargo",
    shortDescription: "Deep black cargo designed for clean streetwear and everyday utility.",
    description: "A sleek midnight cargo with functional detailing and a versatile silhouette designed to move from casual outings to city nights.",
    price: 2299,
    compareAtPrice: 2999,
    costPrice: 940,
    category: "Cargo Pants",
    seoTitle: "BRISTI Midnight Flex Cargo | Premium Black Cargo Pants",
    seoDescription: "Shop the BRISTI Midnight Flex Cargo, premium black cargo pants designed for modern urban style.",
    seoKeywords: "midnight cargo pants, black cargo men, premium streetwear India, utility menswear, BRISTI",
    optionsText: "Color: Midnight, Black | Waist: 30, 32, 34, 36",
  },
  {
    n: 43,
    sku: "BT-SN-001",
    name: "Apex Mono Sneaker",
    shortDescription: "Minimal monochrome sneaker designed for premium everyday styling.",
    description: "A clean low-profile sneaker concept with a versatile monochrome aesthetic, designed to complement tailored trousers, cargos and relaxed denim.",
    price: 3499,
    compareAtPrice: 4499,
    costPrice: 1650,
    category: "Sneakers",
    seoTitle: "BRISTI Apex Mono Sneaker | Premium Men's Sneakers",
    seoDescription: "Shop the BRISTI Apex Mono Sneaker, a premium monochrome men's sneaker designed for versatile modern styling.",
    seoKeywords: "premium men's sneakers, monochrome sneakers, luxury sneakers India, BRISTI footwear, men's fashion",
    optionsText: "Color: Black, White | UK Size: 7, 8, 9, 10, 11",
  },
  {
    n: 44,
    sku: "BT-SN-002",
    name: "Court Ivory Sneaker",
    shortDescription: "Clean ivory sneaker with a refined court-inspired profile.",
    description: "An understated everyday sneaker designed around a clean upper and neutral palette for elevated casual wardrobes.",
    price: 3599,
    compareAtPrice: 4699,
    costPrice: 1700,
    category: "Sneakers",
    seoTitle: "BRISTI Court Ivory Sneaker | Premium Men's Casual Shoes",
    seoDescription: "Discover the BRISTI Court Ivory Sneaker, a premium men's sneaker with a clean neutral profile.",
    seoKeywords: "ivory sneakers men, premium casual shoes, luxury sneakers, white sneakers India, BRISTI",
    optionsText: "Color: Ivory, Cream | UK Size: 7, 8, 9, 10, 11",
  },
  {
    n: 45,
    sku: "BT-SN-003",
    name: "Shadow Runner",
    shortDescription: "Contemporary dark sneaker with a sporty premium silhouette.",
    description: "Designed for modern city movement, the Shadow Runner combines a sleek dark palette with a performance-inspired visual profile.",
    price: 3799,
    compareAtPrice: 4999,
    costPrice: 1850,
    category: "Sneakers",
    seoTitle: "BRISTI Shadow Runner | Premium Men's Sneakers",
    seoDescription: "Shop the BRISTI Shadow Runner, a premium dark men's sneaker with a contemporary runner-inspired silhouette.",
    seoKeywords: "black running style sneakers, premium men's shoes, luxury sneakers India, urban footwear, BRISTI",
    optionsText: "Color: Black, Graphite | UK Size: 7, 8, 9, 10, 11",
  },
  {
    n: 46,
    sku: "BT-SN-004",
    name: "Heritage Court Sneaker",
    shortDescription: "Classic-inspired sneaker reinterpreted with a modern BRISTI aesthetic.",
    description: "A versatile sneaker designed around a timeless court profile and premium neutral colour blocking for everyday sophistication.",
    price: 3699,
    compareAtPrice: 4799,
    costPrice: 1780,
    category: "Sneakers",
    seoTitle: "BRISTI Heritage Court Sneaker | Premium Men's Footwear",
    seoDescription: "Explore the BRISTI Heritage Court Sneaker, a premium men's shoe combining classic court styling with contemporary design.",
    seoKeywords: "heritage sneakers men, premium court shoes, luxury men's footwear, sneakers India, BRISTI",
    optionsText: "Color: White, Tan | UK Size: 7, 8, 9, 10, 11",
  },
  {
    n: 47,
    sku: "BT-AC-001",
    name: "Monogram Leather Belt",
    shortDescription: "Minimal premium belt designed to complete refined everyday looks.",
    description: "A versatile accessory with a clean buckle profile and understated branding, designed to complement BRISTI trousers and tailored separates.",
    price: 1499,
    compareAtPrice: 1999,
    costPrice: 600,
    category: "Accessories",
    seoTitle: "BRISTI Monogram Leather Belt | Premium Men's Accessories",
    seoDescription: "Shop the BRISTI Monogram Leather Belt, a refined premium men's accessory for elevated everyday dressing.",
    seoKeywords: "premium men's belt, luxury leather belt, men's fashion accessories, BRISTI accessories, leather belt India",
    optionsText: "Color: Black, Tan | Waist: 30, 32, 34, 36",
  },
  {
    n: 48,
    sku: "BT-AC-002",
    name: "Noir Fold Wallet",
    shortDescription: "Slim black wallet designed for understated everyday carry.",
    description: "A compact minimalist wallet concept focused on clean lines, practical card storage and a sophisticated black finish.",
    price: 1299,
    compareAtPrice: 1799,
    costPrice: 520,
    category: "Accessories",
    seoTitle: "BRISTI Noir Fold Wallet | Premium Men's Wallet",
    seoDescription: "Discover the BRISTI Noir Fold Wallet, a premium minimalist men's wallet designed for refined everyday carry.",
    seoKeywords: "black men's wallet, premium wallet India, luxury accessories men, minimalist wallet, BRISTI",
    optionsText: "Color: Black | Size: One Size",
  },
  {
    n: 49,
    sku: "BT-AC-003",
    name: "Signature Frame Sunglasses",
    shortDescription: "Modern sunglasses with a clean architectural frame.",
    description: "Designed as a statement accessory, the Signature Frame brings a contemporary shape to everyday looks while maintaining an understated premium character.",
    price: 1799,
    compareAtPrice: 2499,
    costPrice: 720,
    category: "Accessories",
    seoTitle: "BRISTI Signature Frame Sunglasses | Premium Men's Accessories",
    seoDescription: "Shop BRISTI Signature Frame Sunglasses, contemporary premium eyewear designed for modern men's style.",
    seoKeywords: "men's sunglasses, premium sunglasses India, luxury eyewear, fashion accessories men, BRISTI",
    optionsText: "Color: Black, Tortoise | Size: One Size",
  },
  {
    n: 50,
    sku: "BT-AC-004",
    name: "Canvas Weekender Bag",
    shortDescription: "Premium-inspired weekender bag designed for refined short trips and everyday travel.",
    description: "A spacious, versatile carry designed around a clean silhouette, practical storage and a sophisticated neutral aesthetic for modern travel.",
    price: 2999,
    compareAtPrice: 3999,
    costPrice: 1250,
    category: "Accessories",
    seoTitle: "BRISTI Canvas Weekender Bag | Premium Men's Travel Bag",
    seoDescription: "Explore the BRISTI Canvas Weekender Bag, a refined men's travel accessory designed for short trips and elevated everyday carry.",
    seoKeywords: "men's weekender bag, premium travel bag, luxury men's accessories, canvas duffle bag, BRISTI",
    optionsText: "Color: Black, Olive | Size: One Size",
  },
];
