import { body, param } from 'express-validator';

export const createCollectionValidation = [
  body('name').notEmpty().withMessage('Collection name is required').trim(),
  body('slug').optional().trim(),
  body('description').optional().trim(),
  body('shortDescription').optional().trim(),
  body('image').optional().trim(),
  body('bannerImage').optional().trim(),
  body('bannerTablet').optional().trim(),
  body('mobileBanner').optional().trim(),
  body('icon').optional().trim(),
  body('featured').optional().isBoolean().withMessage('featured must be a boolean'),
  body('sortOrder').optional().isInt().withMessage('sortOrder must be an integer'),
  body('isActive').optional().isBoolean().withMessage('isActive must be a boolean'),
  body('showOnHomepage').optional().isBoolean().withMessage('showOnHomepage must be a boolean'),
  body('showInNavigation').optional().isBoolean().withMessage('showInNavigation must be a boolean'),
  body('themeColor').optional().trim(),
  body('buttonColor').optional().trim(),
  body('buttonText').optional().trim(),
  body('seo.title').optional().trim(),
  body('seo.description').optional().trim(),
  body('seo.image').optional().trim(),
];

export const updateCollectionValidation = [
  param('id').isMongoId().withMessage('Invalid collection ID'),
  body('name').optional().trim(),
  body('slug').optional().trim(),
  body('description').optional().trim(),
  body('shortDescription').optional().trim(),
  body('image').optional().trim(),
  body('bannerImage').optional().trim(),
  body('bannerTablet').optional().trim(),
  body('mobileBanner').optional().trim(),
  body('icon').optional().trim(),
  body('featured').optional().isBoolean().withMessage('featured must be a boolean'),
  body('sortOrder').optional().isInt().withMessage('sortOrder must be an integer'),
  body('isActive').optional().isBoolean().withMessage('isActive must be a boolean'),
  body('showOnHomepage').optional().isBoolean().withMessage('showOnHomepage must be a boolean'),
  body('showInNavigation').optional().isBoolean().withMessage('showInNavigation must be a boolean'),
  body('themeColor').optional().trim(),
  body('buttonColor').optional().trim(),
  body('buttonText').optional().trim(),
  body('seo.title').optional().trim(),
  body('seo.description').optional().trim(),
  body('seo.image').optional().trim(),
];
