import { body, param } from 'express-validator';

const slideFieldValidators = (prefix: string) => [
  body(`${prefix}.image`).optional().trim(),
  body(`${prefix}.imageMobile`).optional().trim(),
  body(`${prefix}.video`).optional().trim(),
  body(`${prefix}.videoMobile`).optional().trim(),
  body(`${prefix}.eyebrow`).optional().trim(),
  body(`${prefix}.heading`).optional().trim(),
  body(`${prefix}.headingColor`).optional().trim(),
  body(`${prefix}.showEyebrow`).optional().isBoolean().withMessage('showEyebrow must be a boolean'),
  body(`${prefix}.showCta`).optional().isBoolean().withMessage('showCta must be a boolean'),
  body(`${prefix}.ctaText`).optional().trim(),
  body(`${prefix}.ctaLinkType`).optional().isIn(['collection', 'category', 'product', 'custom']).withMessage('Invalid CTA link type'),
  body(`${prefix}.ctaLink`).optional().trim(),
  body(`${prefix}.description`).optional().trim(),
  body(`${prefix}.secondaryButtonText`).optional().trim(),
  body(`${prefix}.secondaryButtonLink`).optional().trim(),
  body(`${prefix}.backgroundColor`).optional().trim(),
  body(`${prefix}.animationType`).optional().isIn(['fade', 'zoom', 'slide']).withMessage('Invalid animationType'),
  body(`${prefix}.overlay`).optional().isBoolean().withMessage('overlay must be a boolean'),
  body(`${prefix}.overlayOpacity`).optional().isInt({ min: 0, max: 100 }).withMessage('overlayOpacity must be 0-100'),
  body(`${prefix}.gradient`).optional().isBoolean().withMessage('gradient must be a boolean'),
  body(`${prefix}.textAlign`).optional().isIn(['left', 'center', 'right']).withMessage('Invalid textAlign'),
  body(`${prefix}.buttonColor`).optional().trim(),
  body(`${prefix}.animationSpeed`).optional().isFloat({ min: 0.3, max: 5 }).withMessage('animationSpeed must be 0.3-5'),
  body(`${prefix}.priority`).optional().isInt().withMessage('priority must be an integer'),
  body(`${prefix}.visibility.desktop`).optional().isBoolean(),
  body(`${prefix}.visibility.tablet`).optional().isBoolean(),
  body(`${prefix}.visibility.mobile`).optional().isBoolean(),
  body(`${prefix}.status`).optional().isIn(['draft', 'published']).withMessage('Invalid slide status'),
  body(`${prefix}.isActive`).optional().isBoolean().withMessage('isActive must be a boolean'),
  body(`${prefix}.scheduledStart`).optional().isISO8601().withMessage('Invalid scheduledStart date'),
  body(`${prefix}.scheduledEnd`).optional().isISO8601().withMessage('Invalid scheduledEnd date'),
  body(`${prefix}.altText`).optional().trim(),
];

const blockValidators = [
  body('overlay').optional().isBoolean().withMessage('overlay must be a boolean'),
  body('overlayOpacity').optional().isInt({ min: 0, max: 100 }).withMessage('overlayOpacity must be 0-100'),
  body('gradient').optional().isBoolean().withMessage('gradient must be a boolean'),
  body('animationSpeed').optional().isFloat({ min: 0.3, max: 5 }).withMessage('animationSpeed must be 0.3-5'),
  body('priority').optional().isInt().withMessage('priority must be an integer'),
  body('status').optional().isIn(['draft', 'published']).withMessage('Invalid status'),
  body('isActive').optional().isBoolean().withMessage('isActive must be a boolean'),
  /* Legacy flat fields (optional) */
  body('title').optional().trim(),
  body('subtitle').optional().trim(),
  body('description').optional().trim(),
  body('image').optional().trim(),
  body('video').optional().trim(),
  body('imageMobile').optional().trim(),
  body('videoMobile').optional().trim(),
  body('badge').optional().trim(),
  body('primaryButton.label').optional().trim(),
  body('primaryButton.linkType').optional().isIn(['collection', 'category', 'product', 'custom']).withMessage('Invalid link type'),
  body('primaryButton.link').optional().trim(),
  body('secondaryButton.label').optional().trim(),
  body('secondaryButton.linkType').optional().isIn(['collection', 'category', 'product', 'custom']).withMessage('Invalid link type'),
  body('secondaryButton.link').optional().trim(),
  body('contentAlignment').optional().isIn(['left', 'center', 'right']).withMessage('Invalid content alignment'),
  body('textColor').optional().trim(),
  body('buttonColor').optional().trim(),
  body('accentColor').optional().trim(),
  body('animationStyle').optional().isIn(['slide', 'fade', 'kenburns']).withMessage('Invalid animation style'),
  body('visibility.desktop').optional().isBoolean(),
  body('visibility.tablet').optional().isBoolean(),
  body('visibility.mobile').optional().isBoolean(),
  body('seoLabel').optional().trim(),
  body('altText').optional().trim(),
  body('scheduledStart').optional().isISO8601().withMessage('Invalid scheduledStart date'),
  body('scheduledEnd').optional().isISO8601().withMessage('Invalid scheduledEnd date'),
];

export const createHeroValidation = [
  body('name').notEmpty().withMessage('Hero set name is required').trim(),
  body('slides').optional().isArray({ max: 100 }).withMessage('A hero set can contain at most 100 blocks'),
  ...slideFieldValidators('slides.*'),
  ...slideFieldValidators('panels.*.slides.*'),
  body('panels').optional().isArray({ max: 5 }).withMessage('Legacy panels structure: at most 5 panels'),
  body('panels.*.label').optional().trim(),
  body('panels.*.status').optional().isIn(['draft', 'published']).withMessage('Invalid panel status'),
  body('panels.*.isActive').optional().isBoolean().withMessage('isActive must be a boolean'),
  ...blockValidators,
];

export const updateHeroValidation = [
  param('id').isMongoId().withMessage('Invalid hero block ID'),
  body('name').optional().trim(),
  body('slides').optional().isArray({ max: 100 }),
  ...slideFieldValidators('slides.*'),
  ...slideFieldValidators('panels.*.slides.*'),
  body('panels').optional().isArray({ max: 5 }),
  body('panels.*.label').optional().trim(),
  body('panels.*.status').optional().isIn(['draft', 'published']),
  body('panels.*.isActive').optional().isBoolean(),
  ...blockValidators,
];

export const heroIdValidation = [param('id').isMongoId().withMessage('Invalid hero block ID')];
